language: objective-c
osx_image: xcode7.3

env:
  global:
    - GIT_LFS_VERSION="1.1.0"

before_install:
  - brew update > /dev/null && brew install git-lfs && git lfs install && git lfs version

install: true

script: echo hi

